server:
  port: 9090

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/productservice
    username: arunstiwari
    password: Shobhit2401!

  application:
    name: PRODUCT-SERVICE

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost

