server:
  port: 9098

spring:
  application:
    name: PAYMENT-SERVICE

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/