server:
  port: 8900
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:orders
  application:
    name: ORDER-SERVICE
orders:
  paymentservice: http://PAYMENT-SERVICE

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost