server:
  port: 9093

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/cartservice
    username: arunstiwari
    password: Shobhit2401!
  application:
    name: CART-SERVICE
  profiles:
    active: chaos-monkey


chaos:
  monkey:
    enabled: true
    watcher:
      component: false
      controller: false
      repository: false
      rest-controller: true
      service: true
    assaults:
      exceptions-active: false
      kill-application-active: false
      latency-active: true
      latency-range-start: 5000
      latency-range-end: 10000
      level: 1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


carts:
  customerservice: http://localhost:8989
  productservice: http://localhost:8989
management:
  endpoint:
    chaosmonkey:
      enabled: true
    chaosmonkeyjmx:
      enabled: true